### ISSUE TITLE
Enable Signing for MSIs

### ISSUE THREAD

**Issue by compnerd** [compnerd/swift-build#151]
We should sign the MSIs that we are generating for the toolchain.

**Comment by compnerd** [comment]
CC: @wjk 

@wjk would you happen to have any idea on how to accomplish this?  Or have any pointers on enabling signing?

**Comment by wjk** [comment]
As a matter of fact, I do. I'll send in a PR that adds the targets that I use to sign MSIs in my personal projects. Supplying the certificate is up to you, though. 😄

**Comment by compnerd** [comment]
The MSIs are signed as is the installer now.
