### ISSUE TITLE
Publish non-test binaries for Windows SDK

### ISSUE THREAD

**Issue by compnerd** [compnerd/swift-build#160]
We should reorder the build steps for the Windows SDK to publish non-testing enabled binaries.

**Comment by lxbndr** [comment]
I've tried to run Foundation install step before Re-configure for tests, and Test Foundation build fails then.

What if we build Foundation tests in separate working directory? It is full rebuild anyway, no reason to overwrite initial output. And then run install step on original non-test build.

**Comment by compnerd** [comment]
Yeah, I really was hoping to avoid the full rebuild, but since it is a full rebuild, building in a different directory is fine.  Im not sure if that will help though: https://github.com/compnerd/swift-build/commit/3b034ab9d8d986249f853a4345b7b4da24dd7ae0 is where I had tried to reorder the build.  It was conflicting due to the SDK image having the content.  If you can get that to work, that would be great
