### ISSUE TITLE
Can't access //swift/build on Azure DevOps

### ISSUE THREAD

**Issue by the5avage** [compnerd/swift-build#185]
Hi,
i tried to install swift on windows. The instruction says "Install Swift Toolchain from //swift/build.".
I created an account via "sign in with github", but i still can't acess the files.
Error message:
"Your account is not authorized to view this page. Make sure the URL is correct and your account has access."
The link: https://compnerd.visualstudio.com/compnerd/swift-build

**Comment by compnerd** [comment]
You don’t need to create an account to download the artifacts.  You should look at the older docs (docs/Windows.md) or MSDN for instructions on navigating Azure Pipelines.

 If you’re looking for the 5.2 release, it is also attached to this project in the release tab.  The Azure hosted attracts are for the latest releases.
