### ISSUE TITLE
Provide Merge Module for Swift runtime

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#186]
I noticed while looking over the Releases tab that both an EXE bootstrapper and raw MSI files are present. I was wondering if you could also provide a [merge module](https://docs.microsoft.com/en-us/windows/win32/msi/merge-modules) for the Swift runtime. The benefit of this is that merge modules can be embedded within other MSI files, as opposed to top-level MSI files, which can only be bundled with other MSIs using an EXE bootstrapper. I prefer to ship raw MSI files to my users instead of EXE bootstrappers because (a) the built-in MSI install-time UI is much more usable than the one provided by default by the WiX bootstrapper subsystem, and (b) raw MSIs are better supported in enterprise deployment scenarios as compared to installer EXEs. Merge modules are reference-counted by the system, and will not be uninstalled until the last top-level product that embeds them is removed.

You can build a merge module using [the WiX `Module` element](https://wixtoolset.org/documentation/manual/v3/xsd/wix/module.html). I would then suggest editing the runtime MSI file to embed the runtime merge module, and contain no other files.

If you need a hand with this, I can create a PR; I have experience creating and embedding MSMs from one of my non-Swift projects. I just wanted to the idea by you before I started work. Thanks!

**Comment by compnerd** [comment]
Hi @wjk,

I would absolute love to have some help with this!

I didn't know about about merge modules, I've been piecing things together as best as I can.  The one thing that I do wonder - is it possible to install the merge module on its own?  Otherwise, it's kinda unfortunate if you have to do a merge module and the MSI, but it's not the end of the world.

I was kinda saddened at having to do the exe installer, as MSIs are generally better for deployment scenarios, so even if that is more artifacts to worry about, I think that I'd like having a MSI over the EXE installer.

Patches are welcome, it would certainly make this much easier for me.

**Comment by compnerd** [comment]
BTW, I think that it would probably make sense to have a merge module for ICU as well as that needs to be redistributed as well.

**Comment by wjk** [comment]
@compnerd Question for you. Where can I obtain the files that are to be input into the WiX projects? Taking them from an already-installed `C:\Library` doesn’t work, as (a) not all the files that are listed in the wxs file are there, and (b) the files that are present are in a different directory layout. I’d prefer to not have to compile the _entire_ Swift toolchain on my own workstation, but I will if there’s no other choice (and you give me instructions). Thanks!

**Comment by compnerd** [comment]
You should be able to grab the toolchain zip from the azure page for a specific build.  It’s a large download (~2G), but should prevent you from needing to build the toolchain.  In fact, the installer builds are a separate job which use the artifacts from the pipeline.

You can use the google hosted builder pipeline if you like, this is the Microsoft one:

https://dev.azure.com/compnerd/swift-build/_build?definitionId=7

**Comment by wjk** [comment]
Please see my close reasoning in https://github.com/compnerd/swift-build/pull/192#issuecomment-653937043.
