### ISSUE TITLE
"Hello world" program won't compile

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#194]
When I try to compile any Swift file with swiftc, it complains:

```
<unknown>:0: error: unable to load standard library for target 'x86_64-unknown-windows-msvc'`
```

Nothing I do will get it to succeed. This occurs even on `swiftc -c empty.swift` (where empty.swift is a zero-length file). I am using the installer.exe from [this build](https://compnerd.visualstudio.com/swift-build/_build/results?buildId=29243&view=artifacts&type=publishedArtifacts). What am I doing wrong? Thanks!

**Comment by wjk** [comment]
If I add the following flag to the compiler command line, it works just fine:

```
swiftc -sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk -c empty.swift
```

Closing this issue as it is resolved for me.

**Comment by muv1** [comment]
https://github.com/compnerd/swift-build/issues/203
