### ISSUE TITLE
Provide Swift Package Manager?

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#195]
What the title says, really. SwiftPM is used to build most cross-platform Swift programs, and is totally missing in the Windows packages. Unfortunately, this is not as simple as adding a few files into the MSIs; SwiftPM must be built alongside Swift itself. Thanks!

**Comment by compnerd** [comment]
Swift package manager can not really be provided at this time because its not really usable - s-p-m really needs a significant amount of rework to support other platforms.  In the mean time, I recommend that you use CMake.
