### ISSUE TITLE
Consider providing sourcekit-lsp and clangd

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#196]
What the title says, really. These two tools are needed for editor integrations to provide things like autocomplete (which is very important for Swift, given its syntax and idioms). I can't simply compile this myself due to #195. I would appreciate it if these two tools could be installed alongside swift.exe and clang.exe. Thanks!

**Comment by compnerd** [comment]
`clangd` should be possible to add.  SourceKit-LSP is buildable but not usable because of its dependency on s-p-m.
