### ISSUE TITLE
Will there be an IDE? 

### ISSUE THREAD

**Issue by ChlorineX** [compnerd/swift-build#200]
Will this be shipped with a IDE like XCode or a visual studio (not vscode) plugin since setting up the environment in a text editor is complicated (especially when offline)?

**Comment by compnerd** [comment]
No, there’s no plan to integrate an IDE into the installer.  If you’re looking for that, I’d suggest that you take a look at the docker images (https://hub.docker.com/r/compnerd/swift). Improvements to that are welcome.

**Comment by ChlorineX** [comment]
I see. I'm not sure if AppCode will support more platforms as Swift supports more platforms officially. So are there actually a IDE (not text editor) for Swift on non-macos systems?

**Comment by compnerd** [comment]
Right, thats what makes the docker image so interesting :)  It is a Linux environment, but, we can inject the SDKs for different targets.  It is a modified version of VSCode that runs entirely in the docker image, you just need Chrome to connect to it.  You might want to take a look at https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedDocker.md for some brief introductory material.  If you have suggestions to improve that, Im definitely open to that :)

**Comment by ChlorineX** [comment]
Okay, thanks.
