### ISSUE TITLE
Program crashes when using NSCalendar from Foundation

### ISSUE THREAD

**Issue by AriX** [compnerd/swift-build#213]
I got a lot further, but my program crashes when I try to create an NSCalendar.

As an example, I created the following program:
```
import Foundation

if let calendar = NSCalendar(identifier: .gregorian) {
    print("calendar is \(calendar)")
} else {
    print("calendar is nil")
}
```

And built it:
```
export SDKROOT=/c/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk
export SWIFTFLAGS="-sdk $SDKROOT -I $SDKROOT/usr/lib/swift -L $SDKROOT/usr/lib/swift/windows"
/c/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc $SWIFTFLAGS calendar.swift -o calendar.exe
```

When I run it, it crashes:
```
$ ./calendar.exe
Segmentation fault
```

If I debug in Visual Studio, I see:
```
Unhandled exception at 0x00007FF8839E552F (Foundation.dll) in calendar.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

So far, all of my other code that doesn't use NSCalendar works great!

Any tips on how to debug this type of issue?

**Comment by AriX** [comment]
Output from lldb:
```
Process 2652 stopped
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ff8839e552f: Access violation reading location 0x00000000
    frame #0: 0x00007ff8839e552f Foundation.dll`Foundation.NSAffineTransformStruct.init(m11: Foundation.CGFloat, m12: Foundation.CGFloat, m21: Foundation.CGFloat, m22: Foundation.CGFloat, tX: Foundation.CGFloat, tY: Foundation.CGFloat) -> Foundation.NSAffineTransformStruct + 2639
Foundation.dll`Foundation.NSAffineTransformStruct.init(m11: Foundation.CGFloat, m12: Foundation.CGFloat, m21: Foundation.CGFloat, m22: Foundation.CGFloat, tX: Foundation.CGFloat, tY: Foundation.CGFloat) -> Foundation.NSAffineTransformStruct:
->  0x7ff8839e552f <+2639>: callq  *(%rax)
    0x7ff8839e5531 <+2641>: jmp    0x7ff8839e5541            ; <+2657>
    0x7ff8839e5533 <+2643>: movups (%rdx), %xmm0
    0x7ff8839e5536 <+2646>: movups 0x10(%rdx), %xmm1
Target 0: (calendar.exe) stopped.
```

**Comment by AriX** [comment]
Good news; I'm able to work around the problem by using `NSCalendar.current`. Still, it's surprising to me that looking up a calendar by identifier causes a crash. Keeping report open in case the issue is of interest.

**Comment by compnerd** [comment]
hmm, I suspect that the VWT for calendar isnt being initialized?  I know that there are cases like that which are needed for `NSString` to operate correctly.

**Comment by AriX** [comment]
Is there something that I should be doing to get the VWT to initialize?

I will say, everything else is working great now!

**Comment by compnerd** [comment]
Foundation does that normally through its initializer (in a couple of places it does some questionable things to ensure it).  I think that the issue is within Foundation and should be investigated.

Glad to hear that everything else is working great for you!

**Comment by compnerd** [comment]
I'm going to close this off due to the lack of response.  Foundation seems to be generally stable, and if there are still issues, lets track them on the appropriate repository.
