### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by muv1** [compnerd/swift-build#224]
I went here:

https://github.com/compnerd/swift-build/releases/tag/v5.2.1

and I see:

~~~
icu.msi
installer.exe
runtime.msi
sdk.msi
toolchain.msi
~~~

do I need all of these to get started? I am just trying to run a minimal install for Windows. I checked the Readme but didnt see instructions.

**Comment by compnerd** [comment]
Yes, you do need all of them for a minimal install - the toolchain is the toolchain, the SDK is the SDK.  The runtime is the actual Swift runtime; ICU is a dependency for the runtime.

You can use installer.exe to install the full set properly.

The instructions are linked from the README that is displayed on GitHub: https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md

**Comment by muv1** [comment]
If I understand correctly, `installer.exe` is more or less a concatenation of the other 4 files. So a user could just get `installer.exe`, or could get the 4 MSI files.

Is that correct?

**Comment by compnerd** [comment]
Yeah, exactly :)

BTW, PRs to improve the documentation is welcome!
