### ISSUE TITLE
error: 'stdint.h' file not found

### ISSUE THREAD

**Issue by muv1** [compnerd/swift-build#225]
If I get `installer.exe` from here:

https://github.com/compnerd/swift-build/releases/tag/v5.2.1

then install. Then do this:

~~~
set SDKROOT=%SystemDrive%/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk
set SWIFTFLAGS=-sdk %SDKROOT% -I %SDKROOT%/usr/lib/swift -L %SDKROOT%/usr/lib/swift/windows
~~~

Then try this file:

~~~
print("Sunday")
~~~

With `swift a.swift`, I get this:

~~~
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "AssertionReporting.h"
         ^
C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\
   lib\swift\shims/AssertionReporting.h:16:10: note: in file included from
C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\
   lib\swift\shims/AssertionReporting.h:16:
#include "SwiftStdint.h"
         ^
C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\
   lib\swift\shims/SwiftStdint.h:28:10: error: 'stdint.h' file not found
~~~

**Comment by compnerd** [comment]
This feels like you didn’t follow the instructions to copy the module map files into the system.  Can you check that the module map is present?

**Comment by muv1** [comment]
This will have to wait likely for some time. I see now that install requires several large parts of Visual Studio. For example `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` alone is 648 MB. I have been working on packaging a smaller version of Visual Studio:

https://github.com/muv1/sage/blob/master/build-tools.md

Until that happens, I dont use any projects that rely on Visual Studio, on principle.

**Comment by compnerd** [comment]
The SDK and MSVC bits are required as they can’t be redistributed
