### ISSUE TITLE
Program crashes when decoding an integer using Yams

### ISSUE THREAD

**Issue by AriX** [compnerd/swift-build#232]
Running into a frustrating issue. Almost the entirety of my application works on Windows, but it crashes immediately upon decoding an integer from Yaml. I can reproduce this with code as simple as this:
```
let decoder = YAMLDecoder()
print(try decoder.decode(Int32.self, from: "32"))
```

I'm entirely unsure what the problem is - could it be a bug in Yams, CYaml, Swift stdlib, or the Swift compiler? Regardless, it only affects Windows, and the same code works fine on other platforms.

I also don't know how to debug this problem. Visual Studio's debugger doesn't have any awareness of the program's symbols, and lldb won't load (errors like: `C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/lldb.exe: error while loading shared libraries: api-ms-win-crt-utility-l1-1-0.dll: cannot open shared object file: No such file or directory`, and even if I copy those runtime libraries into my working directory, it starts throwing stranger errors, like `C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/lldb.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`). It'd be more tractable to determine the cause if I could use a debugger. Any advice would be appreciated, if you have any!

**Comment by lxbndr** [comment]
Could you try run your Swift app under [WinDbg Preview](https://www.microsoft.com/store/apps/9pgjgd53tn86)? For me it shows better stack traces by default. Mangled, but still readable. Better than nothing.

**Comment by compnerd** [comment]
WinDBG definitely works great in my experience.  Interesting, Ive at least been able to get something out of lldb normally, its unclear why you are getting a failure to load the DLL.

I'll point out that I just added support to run the test suite for Yams from CMake, and was able to get a full run of the test suite on Windows.  The only failing tests are for differences in floating point conversion (value -> special names) which are conforming as per the C standard (`NaN` instead of `nan`, `infe+0` instead of `inf`, etc).

**Comment by AriX** [comment]
Thanks for the tips! Here's what I see in WinDbg (my test program is called "Salad"). Investigating...
<img width="747" alt="Screen Shot 2020-05-18 at 9 50 23 PM" src="https://user-images.githubusercontent.com/398952/82286050-a81b8d00-9951-11ea-8106-cdbb80047da6.png">

**Comment by AriX** [comment]
@compnerd I saw your changes in the Yams project - but it's a mystery to me, how are you getting Yams to build with CMake at the moment? I'm seeing an issue where linking Yams.dll is failing because the compiler can't find the symbols from CYaml.dll:
```
@compnerd I saw your changes in the Yams project - but it's a mystery to me, how are you getting Yams to build with CMake at the moment? I'm seeing an issue where linking Yams.dll is failing because the compiler can't find the symbols from CYaml.dll:
```
Z:\dev\PPackage\Modules\Yams\Yams>cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS="-sdk %SDK% -I %SDK%/usr/lib/swift -L %SDK%/usr/lib/swift/%OS%"
-- The C compiler identification is Clang 10.0.0 with GNU-like command-line
-- The Swift compiler identification is Apple 5.3
-- Check for working C compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/clang.exe
-- Check for working C compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/clang.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe - works
-- Configuring done
-- Generating done
-- Build files have been written to: Z:/dev/PPackage/Modules/Yams/Yams/build

Z:\dev\PPackage\Modules\Yams\Yams>cmake --build build
[1/3] Linking Swift shared library bin\Yams.dll
FAILED: bin/Yams.dll Sources/Yams/CMakeFiles/Yams.dir/Constructor.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Decoder.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Emitter.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Encoder.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Mark.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Node.Mapping.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Node.Scalar.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Node.Sequence.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Node.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Parser.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Representer.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Resolver.swift.obj Sources/Yams/CMakeFiles/Yams.dir/String+Yams.swift.obj Sources/Yams/CMakeFiles/Yams.dir/Tag.swift.obj Sources/Yams/CMakeFiles/Yams.dir/YamlError.swift.obj swift/Yams.swiftmodule lib/Yams.lib
cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map Sources\Yams\CMakeFiles\Yams.dir\Release\output-file-map.json -incremental -j 2 -emit-library -o bin\Yams.dll -module-name Yams -module-link-name Yams -emit-module -emit-module-path swift\Yams.swiftmodule -emit-dependencies -DSWIFT_PACKAGE -DYams_EXPORTS -sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk -I C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk/usr/lib/swift -L C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk/usr/lib/swift/windows -O -libc MD   -enable-testing -I ../Sources/CYaml/include ..\Sources\Yams\Constructor.swift ..\Sources\Yams\Decoder.swift ..\Sources\Yams\Emitter.swift ..\Sources\Yams\Encoder.swift ..\Sources\Yams\Mark.swift ..\Sources\Yams\Node.Mapping.swift ..\Sources\Yams\Node.Scalar.swift ..\Sources\Yams\Node.Sequence.swift ..\Sources\Yams\Node.swift ..\Sources\Yams\Parser.swift ..\Sources\Yams\Representer.swift ..\Sources\Yams\Resolver.swift ..\Sources\Yams\String+Yams.swift ..\Sources\Yams\Tag.swift ..\Sources\Yams\YamlError.swift    -Xlinker -implib:lib\Yams.lib -L Z:/dev/PPackage/Modules/Yams/Yams/build/lib lib/CYaml.lib  -ldispatch.lib  -lFoundation.lib && cd ."
   Creating library lib\Yams.lib and object lib\Yams.exp
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_stream_start_event_initialize referenced in function $s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeysACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_emit referenced in function $s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeysACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_document_start_event_initialize referenced in function $s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeysACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_document_end_event_initialize referenced in function $s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeysACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_stream_end_event_initialize referenced in function $s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeysACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_canonical referenced in function $s4Yams7EmitterC014applyOptionsToB033_ED6AA6759560A6062E809BF7E6589292LLyyF
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_indent referenced in function $s4Yams7EmitterC014applyOptionsToB033_ED6AA6759560A6062E809BF7E6589292LLyyF
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_width referenced in function $s4Yams7EmitterC014applyOptionsToB033_ED6AA6759560A6062E809BF7E6589292LLyyF
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_unicode referenced in function $s4Yams7EmitterC014applyOptionsToB033_ED6AA6759560A6062E809BF7E6589292LLyyF
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_break referenced in function $s4Yams7EmitterC014applyOptionsToB033_ED6AA6759560A6062E809BF7E6589292LLyyF
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_initialize referenced in function $s4Yams7EmitterC7optionsAC7OptionsVvM.resume.0
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_output referenced in function $s4Yams7EmitterC7optionsAC7OptionsVvM.resume.0
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_set_encoding referenced in function $s4Yams7EmitterC7optionsAC7OptionsVvM.resume.0
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_emitter_delete referenced in function $s4Yams7EmitterCfd
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_scalar_event_initialize referenced in function $s4Yams7EmitterC7OptionsV9canonical6indent5width12allowUnicode9lineBreak7version8sortKeysAESb_S2iSbAC04LineJ0OSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_sequence_start_event_initialize referenced in function $s4Yams7EmitterC7OptionsV9canonical6indent5width12allowUnicode9lineBreak7version8sortKeysAESb_S2iSbAC04LineJ0OSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_sequence_end_event_initialize referenced in function $s4Yams7EmitterC7OptionsV9canonical6indent5width12allowUnicode9lineBreak7version8sortKeysAESb_S2iSbAC04LineJ0OSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_mapping_start_event_initialize referenced in function $s4Yams7EmitterC7OptionsV9canonical6indent5width12allowUnicode9lineBreak7version8sortKeysAESb_S2iSbAC04LineJ0OSi5major_Si5minortSgSbtcfC
Emitter.swift.obj : error LNK2019: unresolved external symbol yaml_mapping_end_event_initialize referenced in function $s4Yams7EmitterC7OptionsV9canonical6indent5width12allowUnicode9lineBreak7version8sortKeysAESb_S2iSbAC04LineJ0OSi5major_Si5minortSgSbtcfC
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_parser_initialize referenced in function $s4Yams6ParserC8encodingAC8EncodingOvg
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_parser_set_encoding referenced in function $s4Yams6ParserC8encodingAC8EncodingOvg
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_parser_set_input_string referenced in function $s4Yams6ParserC8encodingAC8EncodingOvg
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_parser_delete referenced in function $s4Yams6ParserCfd
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_parser_parse referenced in function $s4Yams6ParserCfD
Parser.swift.obj : error LNK2019: unresolved external symbol yaml_event_delete referenced in function $s4Yams6ParserC12loadSequence33_61DADACE4404A34EA4A7CBD5917BB545LL4fromAA4NodeOAA5EventAELLC_tKF
bin\Yams.dll : fatal error LNK1120: 25 unresolved externals
clang: error: linker command failed with exit code 1120 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1120 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by compnerd** [comment]
Yams issues are best reported to Yams.  If there’s proof of a compiler issue, The Swift jira with a standalone teaser case demonstrating the problem is appropriate. This repository isn’t a general Windows issue point ;)

The reason you are unable to build yams is because you forgot to pass -D BUILD_SHARED_LIBS=YES

**Comment by AriX** [comment]
Totally fair, and apologies for my obvious abuse of the repo :)

Ultimately I was able to get Yams up-and-running by adding "-DWIN32" to its cflags. For unclear reasons, this wasn't being passed in.

When using Yams .dlls built by cmake, I no longer have the crash that I was seeing earlier, so everything is working great now.

Thanks for the work you're doing on all of these projects!

**Comment by compnerd** [comment]
Great to hear that the problem has resolved itself!  For Windows the only option currently is building with CMake.  I wonder what you were using previously.

And no worries, just wanted to point that out since the other means of raising the issues are more likely to get you more precise help quickly.

**Comment by AriX** [comment]
@compnerd I was invoking `swiftc` myself, and just passing all of the Swift and C files directly to the compiler. It's admittedly not the cleanest way to build, but it did work on other platforms.

**Comment by compnerd** [comment]
Ah, this now makes sense.  Compiling it that way is likely to break, you should use the build systems unless you perfectly replicate them.  I bet that you were actually causing memory corruptions because using the swift driver to compile C code for windows is not going to compile things correctly.

**Comment by AriX** [comment]
Fwiw, I did try a variety of things that I expected would work, such as building the C portions with `clang` and doing the linking separately. But I'm sure you're right, clearly I was missing something that `cmake` knows how to do!
