### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by ataffeqeexo** [compnerd/swift-build#286]
This probably isn't the best place to be asking this, but is there a sense of when Swift for Windows will be ready for more general purpose use? Like to the point where I can just clone a swift repo, the swift package manager resolves everything properly, and I'm just off to the races. Working on porting a macOS/Linux project to Windows and not sure if I'll be able to (in the project's current state) just run Swift or not.

I know 5.2.1 is available, but there are a number of binaries (not entirely sure which I need) with somewhat limited documentation. I think I heard 5.3 was the timeline (which would coincide with Xcode 11), but just wanted to confirm.

Thanks for the work Saleem, just trying to make some business decisions here. I'd love to just use our existing Swift package, but not sure how realistic it is

**Comment by compnerd** [comment]
Hi @ataffeqeexo,

While I can empathize with your position, I'm afraid that I cannot provide any timing information.

If you're interested in the swift-package-manager, the place to track that work is the swift-package-manager repository.  I've tried to work with the projects to get the changes merged, and the builds reflect that - they build from the official repositories, not forks.

However, with regards to documentation, I would be more than happy to improve that!  If there are specific items that you could point out that would be useful to getting started, I'd be happy to expand on those.

I assume that you've seen the [Getting Started](https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md) page that should hopefully explain what the pieces are.

Technically, you would need three of the binaries (installer.exe, icu.msi, runtime.msi), as there are pieces that would need to be redistributed with a binary release like the runtime as there is no pre-installed Swift runtime on the system.  However, if you are intending to release a package as source, you should only need the installer to install the toolchain.

**Comment by ataffeqeexo** [comment]
So the project is setup as a library, with a few dependencies from swift package manager. On macOS, it's just integrated into an Xcode project for a native Mac app. My goal on windows is to create a dll or equivalent to integrate into a native windows app. So I guess I would need to bundle the runtime and icu into that dll? That's the main documentation I'm looking for.

**Comment by compnerd** [comment]
Yes, the runtime and ICU would need to be bundled to provide that.  The MSIs are provided to ease that distribution, assuming that you would want a prebuilt binary with an installer.  If that is the case, the MSIs can be just dropped into a bundle.  Alternatively, you could package up the binaries from the developer installation (they use the same MSIs).

I will have to drop in a bit of legalese here I am afraid: the binaries are provided without warranty.  I am simply providing the builds for ease (there is nothing special in these binaries, and if there are pieces which have slipped through, I would love to know about them as I would like those to be contributed back to the Swift project so that everyone may benefit).

**Comment by ataffeqeexo** [comment]
Got it, and I figured that's the case. So if I was looking to compile this into a DLL, where should I be looking? Follow the getting started page I'm assuming, then can I just run `swift build -c release`? Will that resolve the package manager components or do I need to acquire the package manager parts manually? And will that spit out a DLL or some more Unix looking .a file?

**Comment by compnerd** [comment]
`swift build` is part of swift-package-manager which is still something I am working on.  It would be theoretically possible to wire up the necessary pieces to get swift-package-manager to work.  If you want the tried/tested way, currently that is CMake.

**Comment by compnerd** [comment]
BTW, if you are interested in using swift package manager on Windows, I would suggest that you use the current development builds as there has been a lot of activity on swift package manager as of late.

**Comment by ataffeqeexo** [comment]
Ohh awesome thanks, sorry for not responding to this sooner. Will keep updated with progress

**Comment by ataffeqeexo** [comment]
Can you actually point me in the direction of those downloads? The artifacts from the CI are a bit hidden

**Comment by compnerd** [comment]
https://dev.azure.com/compnerd/swift-build/_build/results?buildId=38323&view=artifacts&type=publishedArtifacts is a recent run.  The `utilities/swift-build.py` script (requires `azure-devops` and `tabulate` python packages) also will also allow you to download the artifacts if you so desire (`swift-build.py --download --build-id VS2019 --latest-artifacts --filter installer.exe`).

**Comment by ataffeqeexo** [comment]
So I'm running into this error when trying to run the basic cmake in the example folder:
```
C:\Users\Alex Taffe\Desktop>build.bat

C:\Users\Alex Taffe\Desktop>set SDKROOT=C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk

C:\Users\Alex Taffe\Desktop>set SWIFTFLAGS=-sdk C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk -I C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift -L C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows

C:\Users\Alex Taffe\Desktop>"C:\Program Files/CMake/bin/cmake.exe" -B /BinaryCache/HelloWorld -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS="-sdk C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk -I C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift -L C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows" -G Ninja -S /SourceCache/swift-build-examples/HelloWorld
-- The C compiler identification is MSVC 19.27.29111.0
-- The Swift compiler identification is Apple 5.3
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe
-- Check for working Swift compiler: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeTestSwiftCompiler.cmake:41 (message):
  The Swift compiler

    "C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin/swiftc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /BinaryCache/HelloWorld/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~2/MICROS~1/2019/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe cmTC_d652a && [1/1] Linking Swift executable cmTC_d652a.exe
    FAILED: cmTC_d652a.exe CMakeFiles/cmTC_d652a.dir/main.swift.obj cmTC_d652a.swiftmodule
    cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map CMakeFiles\cmTC_d652a.dir\\output-file-map.json -incremental -j 8 -emit-executable -o cmTC_d652a.exe -emit-dependencies  -sdk C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk -I C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift -L C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows  -sdk C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk -I C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift -L C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows  main.swift    && cd ."
       Creating library cmTC_d652a.lib and object cmTC_d652a.exp
    LINK : error LNK2001: unresolved external symbol mainCRTStartup
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x86\msvcrt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x86\msvcprt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x86\legacy_stdio_definitions.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
    cmTC_d652a.exe : fatal error LNK1120: 1 unresolved externals
    clang: error: linker command failed with exit code 1120 (use -v to see invocation)
    <unknown>:0: error: link command failed with exit code 1120 (use -v to see invocation)
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/BinaryCache/HelloWorld/CMakeFiles/CMakeOutput.log".
See also "/BinaryCache/HelloWorld/CMakeFiles/CMakeError.log".
```

It seems to be the linker yelling about not having a main entry point, but also seems like there are a few 64 v 32 bit warnings (I doubt those are causing the failure). Ran with that latest artifact you posted. Also sorry for the delay, was on vacation last week,

**Comment by compnerd** [comment]
The mismatch is because you're in the x86 developer command prompt, not x64.  That's the reason for the failure as well.

**Comment by ataffeqeexo** [comment]
Yep, that did it, thanks for the help

**Comment by compnerd** [comment]
I'm going to close this off.  If you run into issues, feel free to create a relevant issue.
