### ISSUE TITLE
LinuxMain test issues

### ISSUE THREAD

**Issue by ataffeqeexo** [compnerd/swift-build#304]
What is the appropriate method for ignoring or correctly running `LinuxMain.swift` in the test folder? I'm getting the following error:
`error: missing LinuxMain.swift file in the Tests directory`

**Comment by ataffeqeexo** [comment]
One solution is to add the`--enable-test-discovery` but this seems less than ideal. For an example: https://github.com/apple/swift-nio-transport-services/issues/106

**Comment by compnerd** [comment]
This isn't the best place for random issues with s-p-m.  This sounds like a SPM issue, bugs.swift.org is the right place to report those.  I suspect that there's a path issue somewhere.  Do you have a stand-alone test case?
