### ISSUE TITLE
Linker failure when including outside C header libraries on 5.3-dev

### ISSUE THREAD

**Issue by dlmarquis** [compnerd/swift-build#317]
I'm using an older snapshot from just before MSVC was removed (LLVM b6c965e56f7a3c6, Swift 50e6ae08bad884e).

I installed the Gnu Scientific Library to `C:\gsl-2.6\gsl`, added it to my `%INCLUDE%`, and put `#include <gsl\gsl_rng.h>` in a C library providing a drand48-equivalent in my Swift project (DDMathParser in the log below). I add this Swift project as a dependency to another Swift project (StateSecrets in the log below). I get a linker failure on the last step, building the .exe, saying it couldn't find several symbols found in gsl_rng.h.

I've pasted a log [here](https://pastebin.com/VfG8J5qS). I've obscured the real names of things in the "StateSecrets" project because some of the code relates to secret work things. Pastebin apparently didn't like the way I obscured things, because it's going to warn you about "potentially sensitive content".

I have also tried including the [SGSL](https://github.com/kongzii/SGSL) Swift library instead. That gives me a `Can't open file: 'gsl.lib'` error, and that looks like it references `gsl.lib` in all the object files even though gsl.lib never gets built itself. I can attach that log as well if you want it.

**Comment by compnerd** [comment]
This is not really the right place for getting help for general Swift usage issues.  The Windows development section on the forums would be better.

You dont include the actual invocation which is important as well as Package.swift - from here it just looks like a user issue - invalid invocation of the tools.

**Comment by dlmarquis** [comment]
I figured it was a Windows-specific bug since this implementation works fine on Mac and Linux for us. In any case we've managed to work around it.
