### ISSUE TITLE
Consider adding a symlink in wix installer for tool_chain_root /usr/lib

### ISSUE THREAD

**Issue by farzonl** [compnerd/swift-build#349]
For windows you have to provide a sdk directory to build a swift file like so: 

`swiftc main.swift -o main.exe -sdk %SDKROOT%" `

This is inconsistent with linux and mac and the artifact of designs decisions handled by tooling that doesn't exist for Windows.

There are good reasons why this is the case, however we can setup a default sdk root for windows in the wix installer without touching apple/swift or breaking any assumptions made by xcrun for the mac.

My proposal is to setup a symlink from:
`C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows `
to:
`C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\windows`

on Windows we can do a symlink like so: `mklink /d  <target dir> <src dir>`

From reading your wix environment variables I believe we could setup a custom wix command to create this symlink like so:

```
# this first block creates the action
<CustomAction Id="makeSymbolicLink" 
   ExeCommand='cmd /c mklink /d "$(var.TOOLCHAIN_ROOT)\usr\lib\swift\windows" "$(var.SDK_ROOT)\usr\lib\swift\windows"' 
   Execute="deferred"
   Impersonate="no"/>

# this calls to the custom action
<Custom Action="makeSymbolicLink" Before="InstallFinalize" />
```

Let me know what you think, thanks,

-FL

**Comment by farzonl** [comment]
As an a side, I don't see any  custom actions in the wix xml so not sure if you are avoiding them. In anycase we could also put it in something like `toolchain-msi.yml`  that you are using in #340. I'm just less familiar with how all that works.

**Comment by farzonl** [comment]
I think that changing the driver to give it a default search path for the SDK makes sense, or perhaps having it honor `SDKROOT`.

_Originally posted by @compnerd in https://github.com/compnerd/swift-build/issues/187#issuecomment-607640404_

So this would be an alternative to changing the driver. My thinking is we could write a tool that works like  pyenv global instead of on a per project basis like how SPM feeds in the sdk. that could switch your default for you by changing the symlink.

**Comment by compnerd** [comment]
I think that changing the driver to honor `SDKROOT` as an environment variable is totally reasonable.

Using a tool to control the environment is reasonable - this is the type of functionality that I would expect to fit in really well with [compnerd/swift-devenv](https://github.com/compnerd/swift-devenv).  I would prefer that `swift-devenv` manage the symbolic link over the installer as the desire is to actually permit the user to not install the Windows SDK at all.  You could install just the Android SDK and the toolchain instead - what would the symbolic link default to then in the installer?
