### ISSUE TITLE
swiftWinSDK.dll missing from the toolchain package

### ISSUE THREAD

**Issue by egorzhdan** [compnerd/swift-build#352]
I've tried running the latest trunk toolchain installer from swift.org (`swift-DEVELOPMENT-SNAPSHOT-03-09-a-windows10.exe`), and the installed toolchain is missing the `Windows.sdk\usr\bin` directory, in particular I can't find `swiftWinSDK.dll` anywhere in the toolchain root.

The missing binaries seem to prevent SwiftPM from launching.

(I'm not 100% sure this is an issue with the Windows installer scripts, it might as well be caused by some change in the Swift CMake logic)

**Comment by compnerd** [comment]
The dll shouldn't be in the toolchain.  That is the SDK overlay runtime component and should be in the runtime.  Check Library\Swift-development\bin, which is where it should be.

**Comment by egorzhdan** [comment]
Thanks a lot @compnerd! Turns out the binaries are indeed under `Swift-development`, and the problem was caused by this directory not being in `Path`.
