### ISSUE TITLE
swift-build uses the wrong archiver program name on Windows

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#375]
When I run `swift-build.exe` in an SPM project that contains a static library product, the Swift sources are compiled, but then the build process fails stating that it cannot find the `ar` program. There is no such program on my PATH, but there is `llvm-ar.exe`, which I understand has the same syntax and semantics as the classic binutils `ar`. I don't know how I would point SPM at the correct archiver executable. Any pointers would be appreciated. Thanks!

**Comment by compnerd** [comment]
This is the wrong place to report issues like that :)  This belongs on the Swift JIRA.  As to the issue here, its not SPM but llbuild.  At the time they were unhappy with using `llvm-ar`, and perhaps that has changed.  In the mean time, you should be able to just do `export AR=llvm-ar`.

**Comment by compnerd** [comment]
Oh, I should mention, this is **COMPLETELY** unsupported.  static linking is not meant for use on Windows.

**Comment by wjk** [comment]
@compnerd Given that static linking is not supported on Windows, how would you suggest linking a CMake-built EXE against SPM output (since Windows EXEs need more build-time work than SPM can provide)? I tried static linking because it works so well on macOS and Linux. If there’s a better technique, I’d love to hear it. Thanks!

**Comment by compnerd** [comment]
That works just fine ;-)  You can see an example of how to build shared libraries from SPM here:
https://github.com/compnerd/swift-com/blob/main/Package.swift#L7-L9 or even at https://github.com/compnerd/swift-win32/blob/main/Package.swift#L8-L9
