### ISSUE TITLE
Manifest parse error under MinGW on Windows

### ISSUE THREAD

**Issue by stevenwdv** [compnerd/swift-build#413]
I'm not sure if this is the right repo, but if not, tell me.
I encountered a problem with the Swift SDK on Windows where it would not properly build from a MinGW shell or a shell started from a MinGW shell. This also applies to e.g. the MinGW `make` utility on Windows. It is caused by MinGW transforming the `Path` environment variable to `PATH` for Unix tools, but apparently swift only accepts `Path`.

Steps to reproduce and to get it to work:
```pwsh
PS> swift package init --type executable
Creating executable package: swtst
Creating Package.swift
Creating README.md
Creating .gitignore
Creating Sources/
Creating Sources\swtst\main.swift
Creating Tests/
Creating Tests\swtstTests/
Creating Tests\swtstTests\swtstTests.swift

PS> swift run
[1/3] Compiling swtst main.swift
[2/4] Merging module swtst
[3/4] Wrapping AST for swtst for debugging
[4/4] Linking C:\my\path\to\swtst\.build\x86_64-unknown-windows-msvc\debug\swtst.exe
[4/4] Build complete!
Hello world!

PS> sh

sh-5.1$ swift run
C:\my\path\to\swtst: error: manifest parse error(s):
Unknown error parsing manifest for swtst

sh-5.1$ powershell -NoLogo

PS (in sh)> swift run
C:\my\path\to\swtst: error: manifest parse error(s):
Unknown error parsing manifest for swtst

PS (in sh)> $p = $env:PATH; $env:PATH = ""; $env:Path = $p  # Transform PATH back to Path

PS (in sh)> swift run
[1/1] Planning build
[0/0] Build complete!
Hello, world!
```

The fix would be to apply case-insenitive matching to the path environment variable.

**Comment by compnerd** [comment]
The MinGW shell is not supported.  The windows support is for windows, not MinGW, even though the latter is on windows.  There are subtle issues which can happen as a result.  MinGW support, AFAIK, is unmaintained in swift.
