### ISSUE TITLE
Question about TensorFlow build

### ISSUE THREAD

**Issue by philipturner** [compnerd/swift-build#418]
On the newest Swift nightlies, swift-apis should be broken. And on the newest Swift releases, _Differentiation is disabled. How did a build succeed on Azure five days ago? Is it using an older version of Swift?

**Comment by compnerd** [comment]
swift-apis are no longer built due to S4TF being archived.  `_Differentiation` is not disabled on the newest builds.

**Comment by philipturner** [comment]
@compnerd if you’re not building swift-apis on Azure, then I’ve had a misunderstanding this whole time. I thought that from ProfFan’s PR’s title, it meant S4TF had suddenly failed to build on Azure, and you were spending time reviewing his commits to make it build on Azure again. I guess I got something wrong there. Did the 5-days ago build just compile CTensorFlow and exclude swift-apis?

If so, why is it even part of “swift-build” when no Swift code is being compiled? I assume it costs money to run those builds, so what purpose does building CTensorFlow (a framework for Python) serve?

If you’re not reviewing that PR for your own purposes, then why did you take time to do it? From what you told me, you are very busy with other projects. Why didn’t you close the PR outright? If S4TF is archived, then modifications should be prohibited.

**Comment by compnerd** [comment]
CTensorFlow hasn't been built in a very long time :)

The review was for getting the repo to build with a newer compiler, as Fan was a colleague, I simply thought I would help get the change through.  It's not because of the builds failing on azure.  The builds there at this point are only those for the standard toolchain.  If Fan gets the toolchain building, I don't mind trying to get an updated build of TF and X10.

**Comment by philipturner** [comment]
That still doesn't answer my question. What was it that "built" 5 days ago? The Swift compiler itself? Some auxiliary library for S4TF? Nothing?

**Comment by compnerd** [comment]
I would suggest you look into the build, because I don't know what build you're referring to.

**Comment by philipturner** [comment]
https://dev.azure.com/compnerd/swift-build/_build/results?buildId=45585&view=results\

I guess I'm mistaken. It says the last build was in December 2020. I don't know how I got the timeframe of 5 days ago!

**Comment by philipturner** [comment]
@compnerd sorry for pinging you but this is related to prior conversation. Is there any chance you will review my PRs to S4TF repositories about the Colab notebooks in the near future? If not, I’d like to know so I can publicize them instead of keeping them hidden on a branch of a fork.

**Comment by philipturner** [comment]
I take it that you are not going to review my pull requests.
